### ISSUE TITLE
Deprecation Warning With Latest Version.

### ISSUE THREAD

**Issue by deech** [kursjan/petitparser2#22] opened 2018-09-04 01:15 UTC
With the latest version of `PetitParser2Gui` in `Pharo 6.1` whenever I click on a node in the `Graph` tab I get the following warning:
```
The method Object>>#name called from PP2ParserBrowser>>#compose has been deprecated.
Implement your own domain representation of an object, or use #asString or #printString instead.

Select Proceed to continue, or close this window to cancel the operation.
```

**Comment by kursjan** [comment] 2018-09-04 09:21
Thanks for reporting this, I will fix as soon as possible... 

Or, of course, relevant pull requests are also welcome,...

**Comment by kursjan** [comment] 2018-09-15 11:14
Hi deech. I tried to reproduce, but I failed :(

As far as I see, all `PP2Node` classes override the `name` selector. And the PP2ParserBrowser is supposed to call `name` on those. But it Is it possible that one of your parsers does not return PP2Node?

Could you please share which object causes the mentioned warning?

**Comment by JurajKubelka** [comment] 2018-09-26 16:26
hi @deech: I cannot reproduce it neither.

**Comment by kursjan** [comment] 2018-10-24 20:05
Closing as obsolete. Please let me know if it is somehow reproducible.

**Closed as completed by kursjan** 2018-10-24 20:05 UTC
